---
title: "Untitled"
author: "Jingyu Fu"
date: "2019/11/8"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
sim_regression = function(n = 30, beta0 = 2, beta1 = 0) {
  
  sim_data = tibble( 
    x = rnorm(n=30, mean = 0, sd = 1),
    y = beta0 + beta1 * x + rnorm(n=30, 0, sqrt(50))
  )

  ls_fit = lm(y ~ x, data = sim_data) %>% broom::tidy() 
  
  tibble(
    beta1 = pull(ls_fit, estimate)[2],
    p_value = pull(ls_fit, p.value)[2]
 )
  
  
  
  n_list = tibble(
  beta_n = c(0,1,2,3,4,5,6)) %>% 
  mutate(
   value = map(.x = beta_n, ~rerun(500, sim_regression( beta1 =.x))))
   

 
n_list = n_list %>% 
  unnest()



proportion = n_list %>% 
  group_by(beta_n) %>% 
  summarise(
   proportion = mean( p_value < 0.05 )/n()
    )



proportion %>% 
ggplot(aes(x = beta_n, y = proportion)) + 
  geom_point() + 
  geom_line()+
  labs(title = "Effect size and power plot",
    x = "Effect size",
    y = "Power",
    caption = "The assocaition bewteen effect size and power") +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```

